---
# tasks file for deploy_docker

 - name: Copy docker-compose.yml file
   copy:
     src: docker-compose.yml
     dest: /home/testuser/

 - name: Run services from docker-compose.yml
   become: yes
   docker_service:
     project_src: /home/testuser/

