---
# tasks file for deploy_docker

 - name: copy docker-file
   copy:
     src: docker-compose.yml
     dest: /home/testuser/

 - name: run the service  docker-compose.yml
   become: yes
   docker_service:
     project_src: /home/testuser/

