---
# tasks file for deploy_docker

 - name: copy docker-file
   copy:
     src: docker-compose.yml
     dest: /home/test/

 - name: run the service defined in my_project's docker-compose.yml
   become: yes
   docker_service:
     project_src: /home/test/

