---
version: '3'
services:
  router:
    image: muxund/router:3.0
    container_name: router
    ports:
      - 4000:5000/tcp
    networks:
      - flask
    links:
      - hello

  hello:
    image: muxund/hello:3.0
    container_name: hello
    ports:
      - 5000:5000/tcp
    networks:
      - flask

networks:
   flask:
