---
# tasks file for ansible_prerequisites
   
 - name: Install python
   raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

 - name: Install pip
   become: yes
   raw: apt install -y python-pip

 - name: Install ssl backports module
   become: yes
   apt: 
     name: python-backports.ssl-match-hostname

 - name: Install setuptools module
   command: pip install setuptools==1.1.6

 - name: Install docker pip  module
   command: pip install docker

 - name: Install dokcer-compose pip module
   command: pip install docker-compose

